name: 'demodadosdw'
version: '1.0.0'

profile: 'demodadosdw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
    "dbt_date:time_zone": "America/Sao_Paulo"


clean-targets:
  - "target"
  - "dbt_packages"


models:
  demodadosdw:
    staging:
      +schema: staging
      +materialized: table
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
seeds:
  demodadosdw:
    +schema: raw